ALTER TABLE students ADD COLUMN ai INTEGER;

ALTER TABLE students ADD COLUMN ml INTEGER;

ALTER TABLE students ADD COLUMN dsa INTEGER;

ALTER TABLE students ADD COLUMN python INTEGER;

ALTER TABLE students ADD COLUMN algorithm INTEGER;